version: '3.8'

services:
  odoo:
    image: odoo:18.0
    container_name: odoo_alfa
    depends_on:
      - db
    environment:
      - ODOO_DB_HOST=db
      - ODOO_DB_PORT=5432
      - ODOO_DB_USER=odoo_user
      - ODOO_DB_PASSWORD=nova_senha
      - ODOO_DB_NAME=odoo_db_alfa
      - ODOO_ADMIN_PASSWORD=admin
    volumes:
      - odoo_data_alfa:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./extra-addons:/var/lib/odoo/extra-addons
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo_alfa.rule=Host(`alfa.isy.one`)"
      - "traefik.http.routers.odoo_alfa.entrypoints=web"
      - "traefik.http.services.odoo_alfa.loadbalancer.server.port=8069"

  db:
    image: postgres:15
    container_name: postgres_alfa
    environment:
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=nova_senha
      - POSTGRES_DB=odoo_db_alfa
    volumes:
      - pgdata_alfa:/var/lib/postgresql/data
    restart: always
    networks:
      - traefik

volumes:
  odoo_data_alfa:
  pgdata_alfa:

networks:
  traefik:
    external: true
